### ISSUE TITLE
Folders support for "My files"

### ISSUE THREAD

**Issue by useretail** [linagora/linshare-core#12]
Is there a way to create folders? If not let it be a feature-request. Thanks

**Comment by fmartin-linagora** [comment]
Hi,
It will be a feature, but not in short term. It is planned in our roadmap as a long term feature, probably for the beginning of the next year. For now, we are focusing on the LinShare v1 missing features. This summer we will work on the upload request feature.

**Comment by fmartin-linagora** [comment]
feature issue already existing in main repository : https://github.com/linagora/linshare/issues/57
