### ISSUE TITLE
Images won't display in mails

### ISSUE THREAD

**Issue by RiceBowlJr** [linagora/linshare-core#13]
When I share a file to a mail account (tested with a Miscrosoft Exchange account and Gmail account), all pictures cannot display and there are some display bug as you can see in the attached screen though.
![linshare_bug_mail_pictures](https://user-images.githubusercontent.com/10711117/27128905-b101791c-5100-11e7-92d6-7a2a7588cdd3.png)

**Comment by fmartin-linagora** [comment]
It should be fix in the next release.

**Comment by fmartin-linagora** [comment]
To fix this problem you must upgrade to [LinShare 2.0.1](http://download.linshare.org/versions/2.0.1/) and load this script https://github.com/linagora/linshare-core/blob/2.0.1-1/src/main/resources/sql/postgresql/reset-default-emails-config.sql

**Comment by RiceBowlJr** [comment]
Nice. Do you plan on put it in the next major release (with no need to execute an update script at installation)?
_I hope you put this in the administrator documentation_ ;)

**Comment by fmartin-linagora** [comment]
Already added to the 2.0.1 changelog, take a look at https://github.com/linagora/linshare/blob/master/CHANGELOG.md. On a fresh install, it is already included/fixed. ;)

**Comment by RiceBowlJr** [comment]
Nice! You should have an extra on your payroll 👅
