### ISSUE TITLE
Mail for file sharing from internal to internal is always English

### ISSUE THREAD

**Issue by RiceBowlJr** [linagora/linshare-core#14]
Hi there,
When I share a file from internal account to another internal account, the mail language is always English, impossible to have another one (like french, that is supported in the GUI).
On the other hand, from internal account to external, it is OK.

**Comment by fmartin-linagora** [comment]
Hi,
I found the problem, it will be fixed in LinShare 2.0.1. Release is planned at the end of the month.
Fred

**Comment by RiceBowlJr** [comment]
Thx Fredounet.
