### ISSUE TITLE
Connect linshare to my local LDAP

### ISSUE THREAD

**Issue by Advocatus** [linagora/linshare-core#15]
Hello,
I have successfully installed Linshare and LDAP to my local ubuntu 16.04 server
I now need to connect Linshare to LDAP, but I can't get the application to connect and pull users information

Please help on this

**Comment by marwanJebahi** [comment]
Hello,
Sorry for delay of answer, the team has been busy lately,
To connect LinShare to your Ldap and synchronize users informations, you just need to open the admin interface -> Domains ->  LDAP connections and the add your LDAP.
Regards,

**Comment by fmartin-linagora** [comment]
Hello,
You can also use the documentation related to linshare-docker (docker-compose) to setup the link between your LDAP and LinShare: https://github.com/linagora/linshare-docker#quick-start

**Comment by fmartin-linagora** [comment]
Without any feedback, I consider this issue resolved by itself.
