### ISSUE TITLE
Workgroup LDAP synchronization has an NPE if a group in LDAP does not have readers

### ISSUE THREAD

**Issue by birdli66** [linagora/linshare-core#17]
We use the new 2.2.0 feature creating workgroups from LDAP group trees.

The following constellation  leads to the exception later:
`
dn: cn=workgroup-specifications (project xy),ou=fileshare,dc=adncc,dc=gro
 ups,dc=top
objectClass: top
objectClass: organizationalRole
cn: workgroup-specifications (adn.adncustzone)

dn: cn=writers,cn=workgroup-specifications (project xy),ou=fileshare,dc=a
 dncc,dc=groups,dc=top
objectClass: top
objectClass: organizationalRole
cn: writers
roleOccupant: uid=martin,ou=emp,ou=people,dc=OrgXy,dc=users,dc=top
`

Exception:
`
[ERROR]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20181011.095000:org.linagora.linshare.ldap.JScriptGroupLdapQuery:dnToObject:The field 'extended_group_member_attr' (ldap attribute : 'roleOccupant') must exist in your ldap directory, it is required by the system.
[ERROR]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20181011.095000:org.linagora.linshare.core.batches.impl.SynchronizeLDAPGroupsInWorkgroupsBatchImpl:execute:Failure during the synchro of the domain with uuida05c6257-f282-4164-a55e-245c902519fc
java.lang.NullPointerException
        at org.linagora.linshare.core.service.impl.LDAPGroupQueryServiceImpl.getMembers(LDAPGroupQueryServiceImpl.java:138)
        at org.linagora.linshare.core.service.impl.LDAPGroupQueryServiceImpl.listMembers(LDAPGroupQueryServiceImpl.java:120)
        at org.linagora.linshare.core.service.impl.LDAPGroupSyncServiceImpl.executeBatch(LDAPGroupSyncServiceImpl.java:274)
        at org.linagora.linshare.core.batches.impl.SynchronizeLDAPGroupsInWorkgroupsBatchImpl.execute(SynchronizeLDAPGroupsInWorkgroupsBatchImpl.java:102)
`

Version: 
linshare_backend tag 2.2.0 from dockerhub.

Workaround: 
Adding a dummy reader to every cn=worker- object to prevent the NPE.
Side-effect of this behavior: If this wokraround user is also a writer or contributor, he does not get the additional privileges but remains a Reader.

Note, that we use this 2nd configuration as a workgroup pattern, because your proposed posixGroup pattern is not supported by our directory (OpenLDAP) and also not according to https://ldapwiki.com/wiki/PosixGroup. You might want to adopt your sample setup and test data at https://github.com/linagora/linshare-core/blob/master/src/apacheds/resources/test.ldif. 
`
[
    {
        "description": "default-group-pattern",
        "groupMember": "member",
        "groupName": "cn",
        "groupPrefix": "workgroup-",
        "label": "Ldap groups",
        "memberFirstName": "givenName",
        "memberLastName": "sn",
        "memberMail": "mail",
        "searchAllGroupsQuery": "ldap.search(baseDn, \"(&(objectClass=posixGroup)(cn=workgroup-*))\");",
        "searchGroupQuery": "ldap.search(baseDn, \"(&(objectClass=posixGroup)(cn=workgroup-\" + pattern + \"))\");",
        "searchPageSize": 100,
        "uuid": "dfaa3523-51b0-423f-bb6d-95d6ecbfcd4c"
    },
    {
        "description": "Workgroup membership management via LDAP groups.",
        "groupMember": "roleOccupant",
        "groupName": "cn",
        "groupPrefix": "workgroup-",
        "label": "sdpidm-groups",
        "memberFirstName": "givenName",
        "memberLastName": "sn",
        "memberMail": "mail",
        "searchAllGroupsQuery": "ldap.search(baseDn, \"(&(objectClass=organizationalRole)(cn=workgroup-*))\");",
        "searchGroupQuery": "ldap.search(baseDn, \"(&(objectClass=organizationalRole)(cn=workgroup-\"+pattern+\"))\");",
        "searchPageSize": 100,
        "uuid": "fbb6d64d-d96f-46d8-9189-76deba98621c"
    }
]
`

Thanks for fixing.

**Comment by alamartiniere-Linagora** [comment]
Hello @birdli66,
Thanks for letting us know about your experience. A ticket has been opened on our side. Expect a quick bug fix for next release.
Alvin

**Comment by birdli66** [comment]
Thx

**Comment by alamartiniere-Linagora** [comment]
Hello @birdli66,

LinShare 2.2.1 is out, fixing this NPE issue.
You can find the changelog of this release [here](https://github.com/linagora/linshare/blob/master/CHANGELOG.md).

Alvin

**Comment by birdli66** [comment]
Great, thx.
