### ISSUE TITLE
Cant Install Schema

### ISSUE THREAD

**Issue by ndcsilent** [linagora/linshare-core#21]
I cant setup schema anybody can help me?
O.S = Centos 7
linshare = 2.3

![psql setup](https://user-images.githubusercontent.com/51688278/67772745-90ec7f00-fa95-11e9-8f40-f2d4abfd9266.png)

**Comment by fmartin-linagora** [comment]
Hello,
`psql -U linshare -W -d linshare < createSchema.sql`
